# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages
bioc_packages:
  - BiocParallel
  - EBImage
r_github_packages:
  - rorynolan/filesstrings
  - rorynolan/autothresholdr
after_success:
  - Rscript -e 'covr::codecov()'
apt_packages:
  - libssl-dev
  - libtiff5-dev
  - libfftw3-dev
  - libcurl4-openssl-dev
  - libxml2-dev
  - default-jre
  - default-jdk
  - libboost-all-dev
