# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: true
cache: packages

apt_packages:
  - libtiff4-dev
  - xclip
  - libgit2-dev

env:
  - TRAVIS_CLIP=xclip DISPLAY=:99.0

before_script:
  - sh -e /etc/init.d/xvfb start
  - sleep 3
  - if [ "$TRAVIS_CLIP" == "xclip" ]; then uptime | xclip -i -sel p -f | xclip -i -sel c; xclip -o -sel clipboard; fi

after_success:
  - travis_wait 30 Rscript -e 'covr::codecov(line_exclusions = "R/nandb.R")'

