# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: true
cache: packages

dist: xenial

apt_packages:
  - libtiff5-dev
  - libgit2-dev

after_success:
  - travis_wait 30 Rscript -e 'covr::codecov()'

before_cache: Rscript -e 'remotes::install_cran("pkgdown")'
deploy:
  provider: script
  script: Rscript -e 'pkgdown::deploy_site_github()'
  skip_cleanup: true
