# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: true
cache: packages

apt_packages:
  - libtiff4-dev

r_github_packages:
  - rorynolan/strex
  - rorynolan/filesstrings
  - ropensci/ijtiff
  - rorynolan/autothresholdr
  - mllg/checkmate
  - rorynolan/detrendr

after_success:
  - travis_wait 30 Rscript -e 'covr::codecov(line_exclusions = "R/nandb.R")'

