# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
sudo: true
cache: packages

env:
  - NOT_CRAN=true

matrix:
  include:
    - os: linux
      dist: xenial
      addons:
        apt:
          update: true
          packages:
            - libtiff5-dev
            - libfftw3-dev
            - libmagick++-dev
            - libgit2-dev
      warnings_are_errors: false
      after_success: Rscript -e 'covr::codecov()'
    - os: osx
      osx_image: xcode12.2
      env: _R_CHECK_LENGTH_1_CONDITION_=true
      r_build_args: --no-build-vignettes --no-manual
      r_check_args: --no-build-vignettes --no-manual
      warnings_are_errors: false
